#!/usr/bin/env bash

# Update package index
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx (without using systemctl)
sudo killall -s HUP nginx &>/dev/null || sudo /usr/sbin/nginx -s reload &>/dev/null

# Create a temporary index.html file containing "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

