#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Define the redirection configuration
cat > /etc/nginx/sites-available/redirect <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /redirect_me {
        return 301 https://example.com/new_page;
    }

    # Additional server configuration can go here
}
EOF

# Enable the redirection configuration
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Test Nginx configuration
nginx -t

# Restart Nginx
service nginx restart

