#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Define the custom 404 page
cat > /etc/nginx/sites-available/custom_404 <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    location / {
        return 404 "Ceci n'est pas une page";
    }

    # Additional server configuration can go here
}
EOF

# Enable the custom 404 configuration
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test Nginx configuration
nginx -t

# Restart Nginx
service nginx restart

