#!/usr/bin/env bash

if ! service nginx status | grep -q "active (running)"
then
    apt-get update
    apt-get install nginx -y
fi

if ! netstat -tuln | grep LISTEN | grep -q ":80"
then
    echo "
    server {
        listen 80;
        listen [::]:80;

        server_name _;

        location / {
            # Your site configuration goes here
        }
    }" > /etc/nginx/sites-available/default

    systemctl reload nginx
fi
