#!/usr/bin/env bash
# Configures Nginx to listen on port 80

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
sleep 1
[ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost)" == "200" ] && echo "Nginx is configured and serving a web page with HTTP 200 status code."

