#!/usr/bin/env bash
# This script connects to the server using ssh with a private key

# Connect to the server using the private key ~/.ssh/school and the user ubuntu
ssh -i ~/.ssh/school ubuntu@100.25.142.221

